apiVersion: v1
kind: Service
metadata:
  name: hmis-backend
  namespace: hmis-prod
  labels:
    app: hmis-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP  # Internal service (exposed via Ingress)
  selector:
    app: hmis-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  sessionAffinity: None
