apiVersion: v1
kind: Service
metadata:
  name: hmis-frontend
  namespace: hmis-prod
  labels:
    app: hmis-frontend
spec:
  type: ClusterIP
  selector:
    app: hmis-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
